name: scribble
description: Scribble is a lightweight library for freehand drawing in Flutter supporting pressure, variable line width and more!
version: 0.0.4
repository: https://github.com/timcreatedit/scribble

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  vector_math: ^2.1.0
  freezed_annotation: ^0.14.3
  flutter_state_notifier: ^0.7.1
  kimchi: ^0.0.9

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.1
  freezed: ^0.14.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
